stages:
  - build
  - deploy

variables:
  CI_PROJECT_NAME: youdescribex-api
  DOCKER_REGISTRY: youdescribe
  CI_REGISTRY: docker.io
  IMAGE_NAME: "${DOCKER_REGISTRY}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}.${CI_PIPELINE_ID}"

services:
  - docker:24.0.5-dind

before_script:
  - echo "Logging into Docker..."
  - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USER" --password-stdin $CI_REGISTRY

build:
  stage: build
  script:
    - echo "Building Docker image..."
    - docker build --no-cache
      --build-arg GOOGLE_CRED_FILE=$GOOGLE_CRED_FILE
      --build-arg GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS
      -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
    - echo "Build complete"
  tags:
    - backend
  only:
    - dev
    - main

.deploy_template: &deploy_template
  stage: deploy
  script:
    - echo "Deploying to $CI_ENVIRONMENT_NAME environment..."
    - docker-compose -f docker-compose.yml pull
    - docker-compose -f docker-compose.yml down
    - docker-compose -f docker-compose.yml up -d

deploy_dev:
  <<: *deploy_template
  environment:
    name: dev
  variables:
    PASSPORT_REDIRECT_URL: $PASSPORT_REDIRECT_URL_DEV
    PASSPORT_CALLBACK_URL: $PASSPORT_CALLBACK_URL_DEV
    CURRENT_YDX_HOST: $YDX_HOST_DEV
  tags:
    - backend
    - dev
  only:
    - dev

deploy_prod:
  <<: *deploy_template
  environment:
    name: prod
  variables:
    PASSPORT_REDIRECT_URL: $PASSPORT_REDIRECT_URL_PROD
    PASSPORT_CALLBACK_URL: $PASSPORT_CALLBACK_URL_PROD
    CURRENT_YDX_HOST: $YDX_HOST_PROD
  tags:
    - backend
    - prod
  only:
    - main