stages:
  - build
  - deploy
  - cleanup

variables:
  CI_PROJECT_NAME: youdescribex-api
  DOCKER_REGISTRY: youdescribe
  CI_REGISTRY: docker.io
  IMAGE_NAME: "${DOCKER_REGISTRY}/${CI_PROJECT_NAME}"
  LATEST_IMAGE: "${IMAGE_NAME}:latest"

services:
  - docker:24.0.5-dind

before_script:
  - echo "Using pre-installed Docker Compose..."
  - docker-compose --version
  - echo "Logging into Docker..."
  - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USER" --password-stdin $CI_REGISTRY

.build_template: &build_template
  stage: build
  script:
    - echo "Building Docker image..."
    - docker build --no-cache
      --build-arg OPENAI_API_KEY="$OPENAI_API_KEY"
      --build-arg GOOGLE_CRED_FILE="$GOOGLE_CRED_FILE"
      --build-arg GOOGLE_APPLICATION_CREDENTIALS="$GOOGLE_APPLICATION_CREDENTIALS"
      --build-arg NODE_ENV="$NODE_ENV"
      --build-arg YOUTUBE_API_URL="$YOUTUBE_API_URL"
      --build-arg YOUTUBE_API_KEY="$YOUTUBE_API_KEY"
      --build-arg CURRENT_DATABASE="$CURRENT_DATABASE"
      --build-arg POSTGRES_DB_NAME="$POSTGRES_DB_NAME"
      --build-arg POSTGRES_DB_USER="$POSTGRES_DB_USER"
      --build-arg POSTGRES_DB_PASSWORD="$POSTGRES_DB_PASSWORD"
      --build-arg POSTGRES_DB_PORT="$POSTGRES_DB_PORT"
      --build-arg POSTGRES_DB_HOST="$POSTGRES_DB_HOST"
      --build-arg MONGO_DB_DATABASE="$MONGO_DB_DATABASE"
      --build-arg MONGO_DB_HOST="$MONGO_DB_HOST"
      --build-arg MONGO_DB_PORT="$MONGO_DB_PORT"
      --build-arg MONGO_DB_USER="$MONGO_DB_USER"
      --build-arg MONGO_DB_PASSWORD="$MONGO_DB_PASSWORD"
      --build-arg YOUTUBE_API_CREDENTIALS_FILE="$YOUTUBE_API_CREDENTIALS_FILE"
      --build-arg YOUTUBE_API_CREDENTIALS_PATH="$YOUTUBE_API_CREDENTIALS_PATH"
      --build-arg VISION_API_CREDENTIALS_FILE="$VISION_API_CREDENTIALS_FILE"
      --build-arg VISION_API_CREDENTIALS_PATH="$VISION_API_CREDENTIALS_PATH"
      --build-arg TTS_API_CREDENTIALS_FILE="$TTS_API_CREDENTIALS_FILE"
      --build-arg TTS_API_CREDENTIALS_PATH="$TTS_API_CREDENTIALS_PATH"
      --build-arg STT_API_CREDENTIALS_FILE="$STT_API_CREDENTIALS_FILE"
      --build-arg STT_API_CREDENTIALS_PATH="$STT_API_CREDENTIALS_PATH"
      -t $LATEST_IMAGE .
    - docker push $LATEST_IMAGE
    - echo "Build complete"

build_dev:
  <<: *build_template
  tags:
    - backend
    - dev
  only:
    - dev

build_prod:
  <<: *build_template
  tags:
    - backend
    - prod
  only:
    - main

.deploy_template: &deploy_template
  stage: deploy
  retry: 2
  script:
    - echo "Deploying to $CI_ENVIRONMENT_NAME environment..."
    - docker-compose --version
    - docker-compose -f docker-compose.yml config
    - docker-compose -f docker-compose.yml pull || { echo "Failed to pull images"; exit 1; }
    - docker-compose -f docker-compose.yml down || { echo "Failed to stop existing containers"; exit 1; }
    - docker-compose -f docker-compose.yml up -d --remove-orphans || { echo "Failed to start containers"; exit 1; }
    - docker-compose -f docker-compose.yml ps

deploy_dev:
  <<: *deploy_template
  environment:
    name: dev
  variables:
    PASSPORT_REDIRECT_URL: $PASSPORT_REDIRECT_URL_DEV
    PASSPORT_CALLBACK_URL: $PASSPORT_CALLBACK_URL_DEV
    CURRENT_YDX_HOST: $YDX_HOST_DEV
  tags:
    - backend
    - dev
  only:
    - dev
  dependencies:
    - build_dev

deploy_prod:
  <<: *deploy_template
  environment:
    name: prod
  variables:
    PASSPORT_REDIRECT_URL: $PASSPORT_REDIRECT_URL_PROD
    PASSPORT_CALLBACK_URL: $PASSPORT_CALLBACK_URL_PROD
    CURRENT_YDX_HOST: $YDX_HOST_PROD
  tags:
    - backend
    - prod
  only:
    - main
  dependencies:
    - build_prod

cleanup:
  stage: cleanup
  script:
    - echo "Cleaning up old images..."
    - docker images --format "{{.ID}} {{.Repository}}" | grep "${DOCKER_REGISTRY}/${CI_PROJECT_NAME}" | sort -k2 | awk 'NR>1 {print $1}' | xargs -r docker rmi
    - docker container prune -f
    - docker image prune -af
  tags:
    - backend
  rules:
    - if: $CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "main"
      when: always