variables:
  CI_PROJECT_NAME: youdescribex-api
  DOCKER_REGISTRY: youdescribe
  S3_BUCKET: youdescribexci
  S3_PATH: youdescribex-api
  CI_REGISTRY: docker.io
  DOCKER_IMAGE_TAG: "${DOCKER_REGISTRY}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}.${CI_PIPELINE_ID}"

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build-stage:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  tags:
    - backend
    - dev
  before_script:
    - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" $CI_REGISTRY
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
      when: always
  script:
    - echo "Building YouDescribeX Backend in staging"
    - docker build --no-cache --build-arg APP_PORT=$PORT --build-arg GOOGLE_CRED_FILE=$GOOGLE_CRED_FILE --build-arg GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS --build-arg GPU_PIPELINE_PORT=$GPU_PIPELINE_PORT --build-arg CRYPTO_SEED=$CRYPTO_SEED -t "${DOCKER_IMAGE_TAG}" .
    - docker push "${DOCKER_IMAGE_TAG}"
    - echo "Build complete"

build-prod:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  tags:
    - backend
    - prod
  before_script:
    - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" $CI_REGISTRY
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
  script:
    - echo "Building YouDescribeX Backend in prod"
    - docker build --no-cache --build-arg APP_PORT=$PORT --build-arg GOOGLE_CRED_FILE=$GOOGLE_CRED_FILE --build-arg GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS --build-arg GPU_PIPELINE_PORT=$GPU_PIPELINE_PORT --build-arg CRYPTO_SEED=$CRYPTO_SEED -t "${DOCKER_IMAGE_TAG}" .
    - docker push "${DOCKER_IMAGE_TAG}"
    - echo "Build completed"

deploy-stage:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  tags:
    - backend
    - dev
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
      when: on_success
  script:
    - echo "Deploying YouDescribeX Backend build to staging"
    - docker compose down
    - docker compose up -d
    - echo "Deployment to staging completed"

deploy-prod:
  stage: deploy
  tags:
    - backend
    - prod
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: on_success
  script:
    - echo "Deploying YouDescribeX Backend build to production"
    - docker compose down
    - docker compose up -d
    - echo "Deployment to production completed"
