variables:
  CI_PROJECT_NAME: youdescribex-api
  DOCKER_REGISTRY: youdescribe
  S3_BUCKET: youdescribexci
  S3_PATH: youdescribex-api
  CI_REGISTRY: docker.io
  TAR_FILE_NAME: "youdescribex-api.tar"
  TAR_FILE_FOLDER: ".docker"
  TAR_FILE_PATH: "/"
  DOCKER_IMAGE_TAG: "${DOCKER_REGISTRY}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}"

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build-template:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  tags:
    - saas-linux-large-amd64
  before_script:
    - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - echo "This is a placeholder script in the build-template job."

build-staging:
  extends: build-template
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
      when: always
  script:
    - echo "Building YouDescribe Backend in staging"
    - docker build --no-cache --build-arg APP_PORT=$PORT --build-arg GPU_PIPELINE_PORT=$GPU_PIPELINE_PORT -t "${DOCKER_IMAGE_TAG}" .
    - docker push "${DOCKER_IMAGE_TAG}"
    - echo "Build complete"

build-prod:
  extends: build-template
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
  script:
    - echo "Building YouDescribe Backend in prod"
    - docker build --build-arg APP_PORT=$PORT -t "${DOCKER_IMAGE_TAG}" .
    - docker push "${DOCKER_IMAGE_TAG}"
    - echo "Build completed"
