stages:
  - build
  - deploy

variables:
  CI_PROJECT_NAME: youdescribex-api
  DOCKER_REGISTRY: youdescribe
  CI_REGISTRY: docker.io
  TAR_FILE_NAME: "youdescribex-api.tar"
  TAR_FILE_FOLDER: ".docker"
  TAR_FILE_PATH: "/"
  IMAGE_NAME: "${DOCKER_REGISTRY}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}.${CI_PIPELINE_ID}"

services:
  - docker:24.0.5-dind

before_script:
  - echo "Logging into Docker..."
  - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" $CI_REGISTRY
  - docker info

build_dev:
  stage: build
  script:
    - echo "Building Docker image for development..."
    - docker build --no-cache --build-arg APP_PORT=$PORT --build-arg GOOGLE_CRED_FILE=$GOOGLE_CRED_FILE --build-arg GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS --build-arg GPU_PIPELINE_PORT=$GPU_PIPELINE_PORT --build-arg CRYPTO_SEED=$CRYPTO_SEED -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
    - echo "Build complete"
  tags:
    - backend
    - dev
  only:
    - dev

build_prod:
  stage: build
  script:
    - echo "Building Docker image for production..."
    - docker build --no-cache --build-arg APP_PORT=$PORT --build-arg GOOGLE_CRED_FILE=$GOOGLE_CRED_FILE --build-arg GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS --build-arg GPU_PIPELINE_PORT=$GPU_PIPELINE_PORT --build-arg CRYPTO_SEED=$CRYPTO_SEED -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
    - echo "Build complete"
  tags:
    - backend
    - prod
  only:
    - main

deploy_dev:
  stage: deploy
  script:
    - echo "Deploying to development environment..."
    - docker-compose -f docker-compose-dev.yml pull
    - docker-compose -f docker-compose-dev.yml down
    - docker-compose -f docker-compose-dev.yml up -d
  tags:
    - backend
    - dev
  only:
    - dev

deploy_prod:
  stage: deploy
  script:
    - echo "Deploying to production environment..."
    - docker-compose -f docker-compose-prod.yml pull
    - docker-compose -f docker-compose-prod.yml down
    - docker-compose -f docker-compose-prod.yml up -d
  tags:
    - backend
    - prod
  only:
    - main