version: '3'

services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=30
      - WATCHTOWER_LABEL_ENABLE=true
    restart: always


  youdescribe-docs:
      image: youdescribe/youdescribe-docs:master.1114783926
      restart: always
      ports:
        - "0.0.0.0:4321:4321"
      labels:
        - "com.centurylinklabs.watchtower.enable=true"

  youdescribex-app:
      image: youdescribe/youdescribex-app:dev.1209511398
      restart: always
      ports:
        - "0.0.0.0:3001:3001"
      labels:
        - "com.centurylinklabs.watchtower.enable=true"

  youdescribex-api:
    image: youdescribe/youdescribex-api:dev
    restart: always
    ports:
      - "4001:4001"
    extra_hosts:
       - "host.docker.internal:host-gateway"
    network_mode: host
    volumes:
      - "/mnt/ebs/audio-descriptions-files:/app/public"
      - "/home/ubuntu/ydx_data/logs:/app/logs"
    environment:
      - INFISICAL_TOKEN=${INFISICAL_TOKEN}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"