FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ARG GOOGLE_CRED_FILE
ARG GOOGLE_APPLICATION_CREDENTIALS
ENV GOOGLE_CRED_FILE=${GOOGLE_CRED_FILE}
ENV GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}

RUN npm run build
RUN npm prune --production

RUN echo "$GOOGLE_CRED_FILE" | base64 -d -i - > "$GOOGLE_APPLICATION_CREDENTIALS"

CMD ["node", "./dist/server.js"]