version: '3'
services:
  backend:
    container_name: youdescribe-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
      - "${GPU_PIPELINE_PORT}:${GPU_PIPELINE_PORT}"
    volumes:
      - /home/ubuntu/ydx_data/public:/app/public
      - /home/ubuntu/ydx_data/logs:/app/logs
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - HOST=${HOST}
      - LOG_DIR=${LOG_DIR}
      - AUDIO_DIRECTORY=${AUDIO_DIRECTORY}
      - YOUTUBE_API_URL=${YOUTUBE_API_URL}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - PASSPORT_REDIRECT_URL=${PASSPORT_REDIRECT_URL}
      - PASSPORT_CALLBACK_URL=${PASSPORT_CALLBACK_URL}
      - CRYPTO_SECRET=${CRYPTO_SECRET}
      - CRYPTO_SEED=${CRYPTO_SEED}
      - CURRENT_DATABASE=${CURRENT_DATABASE}
      - POSTGRES_DB_NAME=${POSTGRES_DB_NAME}
      - POSTGRES_DB_USER=${POSTGRES_DB_USER}
      - POSTGRES_DB_PASSWORD=${POSTGRES_DB_PASSWORD}
      - POSTGRES_DB_PORT=${POSTGRES_DB_PORT}
      - POSTGRES_DB_HOST=${POSTGRES_DB_HOST}
      - MONGO_DB_DATABASE=${MONGO_DB_DATABASE}
      - MONGO_DB_HOST=${MONGO_DB_HOST}
      - MONGO_DB_PORT=${MONGO_DB_PORT}
      - MONGO_DB_USER=${MONGO_DB_USER}
      - MONGO_DB_PASSWORD=${MONGO_DB_PASSWORD}
