FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

ARG GOOGLE_CRED_FILE
ARG GOOGLE_APPLICATION_CREDENTIALS
ARG NODE_ENV
ARG YOUTUBE_API_URL
ARG YOUTUBE_API_KEY
ARG CURRENT_DATABASE
ARG POSTGRES_DB_NAME
ARG POSTGRES_DB_USER
ARG POSTGRES_DB_PASSWORD
ARG POSTGRES_DB_PORT
ARG POSTGRES_DB_HOST
ARG MONGO_DB_DATABASE
ARG MONGO_DB_HOST
ARG MONGO_DB_PORT
ARG MONGO_DB_USER
ARG MONGO_DB_PASSWORD

ENV GOOGLE_CRED_FILE=${GOOGLE_CRED_FILE}
ENV GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
ENV NODE_ENV=${NODE_ENV}
ENV YOUTUBE_API_URL=${YOUTUBE_API_URL}
ENV YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
ENV CURRENT_DATABASE=${CURRENT_DATABASE}
ENV POSTGRES_DB_NAME=${POSTGRES_DB_NAME}
ENV POSTGRES_DB_USER=${POSTGRES_DB_USER}
ENV POSTGRES_DB_PASSWORD=${POSTGRES_DB_PASSWORD}
ENV POSTGRES_DB_PORT=${POSTGRES_DB_PORT}
ENV POSTGRES_DB_HOST=${POSTGRES_DB_HOST}
ENV MONGO_DB_DATABASE=${MONGO_DB_DATABASE}
ENV MONGO_DB_HOST=${MONGO_DB_HOST}
ENV MONGO_DB_PORT=${MONGO_DB_PORT}
ENV MONGO_DB_USER=${MONGO_DB_USER}
ENV MONGO_DB_PASSWORD=${MONGO_DB_PASSWORD}

RUN npm run build
RUN npm prune --production

RUN if [ -n "$GOOGLE_APPLICATION_CREDENTIALS" ] && [ -n "$GOOGLE_CRED_FILE" ]; then \
        mkdir -p $(dirname "$GOOGLE_APPLICATION_CREDENTIALS") && \
        echo "$GOOGLE_CRED_FILE" | base64 -d > "$GOOGLE_APPLICATION_CREDENTIALS"; \
    else \
        echo "Skipping Google credentials setup"; \
    fi \

CMD ["node", "./dist/server.js"]