version: '3'

services:
  backend:
    container_name: youdescribex-backend
    image: "${DOCKER_REGISTRY}/${CI_PROJECT_NAME}:latest"
    restart: always
    ports:
      - "${PORT}:${PORT}"
      - "${GPU_PIPELINE_PORT}:${GPU_PIPELINE_PORT}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    network_mode: host
    volumes:
      - /home/ubuntu/ydx_data/logs:/app/logs
      - /mnt/ebs/audio-descriptions-files:/app/public
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_CRED_FILE=${GOOGLE_CRED_FILE}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - HOST=${HOST}
      - LOG_DIR=${LOG_DIR}
      - AUDIO_DIRECTORY=${AUDIO_DIRECTORY}
      - YOUTUBE_API_URL=${YOUTUBE_API_URL}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - PASSPORT_REDIRECT_URL=${PASSPORT_REDIRECT_URL}
      - PASSPORT_CALLBACK_URL=${PASSPORT_CALLBACK_URL}
      - CRYPTO_SECRET=${CRYPTO_SECRET}
      - CRYPTO_SEED=${CRYPTO_SEED}
      - CURRENT_DATABASE=${CURRENT_DATABASE}
      - POSTGRES_DB_NAME=${POSTGRES_DB_NAME}
      - POSTGRES_DB_USER=${POSTGRES_DB_USER}
      - POSTGRES_DB_PASSWORD=${POSTGRES_DB_PASSWORD}
      - POSTGRES_DB_PORT=${POSTGRES_DB_PORT}
      - POSTGRES_DB_HOST=${POSTGRES_DB_HOST}
      - MONGO_DB_DATABASE=${MONGO_DB_DATABASE}
      - MONGO_DB_HOST=${MONGO_DB_HOST}
      - MONGO_DB_PORT=${MONGO_DB_PORT}
      - MONGO_DB_USER=${MONGO_DB_USER}
      - MONGO_DB_PASSWORD=${MONGO_DB_PASSWORD}
      - GPU_HOST=${GPU_HOST}
      - GPU_PIPELINE_PORT=${GPU_PIPELINE_PORT}
      - CURRENT_YDX_HOST=${CURRENT_YDX_HOST}
      - GMAIL_USER=${GMAIL_USER}
      - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}
      - AI_USER_ID=${AI_USER_ID}
      - YOUTUBE_API_CREDENTIALS_FILE=${YOUTUBE_API_CREDENTIALS_FILE}
      - YOUTUBE_API_CREDENTIALS_PATH=${YOUTUBE_API_CREDENTIALS_PATH}
      - VISION_API_CREDENTIALS_FILE=${VISION_API_CREDENTIALS_FILE}
      - VISION_API_CREDENTIALS_PATH=${VISION_API_CREDENTIALS_PATH}
      - TTS_API_CREDENTIALS_FILE=${TTS_API_CREDENTIALS_FILE}
      - TTS_API_CREDENTIALS_PATH=${TTS_API_CREDENTIALS_PATH}
      - STT_API_CREDENTIALS_FILE=${STT_API_CREDENTIALS_FILE}
      - STT_API_CREDENTIALS_PATH=${STT_API_CREDENTIALS_PATH}
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"