version: '3'

services:
  backend:
    container_name: youdescribex-backend
    image: "${DOCKER_REGISTRY}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}.${CI_PIPELINE_ID}"
    restart: always
    ports:
      - "${PORT}:${PORT}"
      - "${GPU_PIPELINE_PORT}:${GPU_PIPELINE_PORT}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    network_mode: host
    volumes:
      - /home/ubuntu/ydx_data/public:/app/public
      - /home/ubuntu/ydx_data/logs:/app/logs
      - /mnt/ebs/audio-descriptions-files:/app/public
    environment:
      - GOOGLE_CRED_FILE
      - GOOGLE_APPLICATION_CREDENTIALS
      - PORT
      - NODE_ENV
      - HOST
      - LOG_DIR
      - AUDIO_DIRECTORY
      - YOUTUBE_API_URL
      - YOUTUBE_API_KEY
      - PASSPORT_REDIRECT_URL
      - PASSPORT_CALLBACK_URL
      - CRYPTO_SECRET
      - CRYPTO_SEED
      - CURRENT_DATABASE
      - POSTGRES_DB_NAME
      - POSTGRES_DB_USER
      - POSTGRES_DB_PASSWORD
      - POSTGRES_DB_PORT
      - POSTGRES_DB_HOST
      - MONGO_DB_DATABASE
      - MONGO_DB_HOST
      - MONGO_DB_PORT
      - MONGO_DB_USER
      - MONGO_DB_PASSWORD
      - GPU_HOST
      - GPU_PIPELINE_PORT
      - CURRENT_YDX_HOST
      - GMAIL_USER
      - GMAIL_PASSWORD
      - AI_USER_ID