version: '3.4'

services:
  backend:
    container_name: youdescribex-backend
    image: "${DOCKER_REGISTRY}/${CI_PROJECT_NAME}:latest"
    ports:
      - "${PORT}:${PORT}"
      - "${GPU_PIPELINE_PORT}:${GPU_PIPELINE_PORT}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    network_mode: host
    depends_on:
      - coqui-tts
    volumes:
      - /home/ubuntu/ydx_data/logs:/app/logs
      - /mnt/ebs/audio-descriptions-files:/app/public
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - HOST=${HOST}
      - LOG_DIR=${LOG_DIR}
      - AUDIO_DIRECTORY=${AUDIO_DIRECTORY}
      - YOUTUBE_API_URL=${YOUTUBE_API_URL}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - PASSPORT_REDIRECT_URL=${PASSPORT_REDIRECT_URL}
      - PASSPORT_CALLBACK_URL=${PASSPORT_CALLBACK_URL}
      - CRYPTO_SECRET=${CRYPTO_SECRET}
      - CRYPTO_SEED=${CRYPTO_SEED}
      - CURRENT_DATABASE=${CURRENT_DATABASE}
      - POSTGRES_DB_NAME=${POSTGRES_DB_NAME}
      - POSTGRES_DB_USER=${POSTGRES_DB_USER}
      - POSTGRES_DB_PASSWORD=${POSTGRES_DB_PASSWORD}
      - POSTGRES_DB_PORT=${POSTGRES_DB_PORT}
      - POSTGRES_DB_HOST=${POSTGRES_DB_HOST}
      - MONGO_DB_DATABASE=${MONGO_DB_DATABASE}
      - MONGO_DB_HOST=${MONGO_DB_HOST}
      - MONGO_DB_PORT=${MONGO_DB_PORT}
      - MONGO_DB_USER=${MONGO_DB_USER}
      - MONGO_DB_PASSWORD=${MONGO_DB_PASSWORD}
      - GPU_HOST=${GPU_HOST}
      - GPU_PIPELINE_PORT=${GPU_PIPELINE_PORT}
      - CURRENT_YDX_HOST=${CURRENT_YDX_HOST}
      - GMAIL_USER=${GMAIL_USER}
      - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}
      - AI_USER_ID=${AI_USER_ID}
      - YOUTUBE_API_CREDENTIALS_FILE=${YOUTUBE_API_CREDENTIALS_FILE}
      - YOUTUBE_API_CREDENTIALS_PATH=${YOUTUBE_API_CREDENTIALS_PATH}
      - VISION_API_CREDENTIALS_FILE=${VISION_API_CREDENTIALS_FILE}
      - VISION_API_CREDENTIALS_PATH=${VISION_API_CREDENTIALS_PATH}
      - TTS_API_CREDENTIALS_FILE=${TTS_API_CREDENTIALS_FILE}
      - TTS_API_CREDENTIALS_PATH=${TTS_API_CREDENTIALS_PATH}
      - STT_API_CREDENTIALS_FILE=${STT_API_CREDENTIALS_FILE}
      - STT_API_CREDENTIALS_PATH=${STT_API_CREDENTIALS_PATH}
      - APPLE_REDIRECT_URL=${APPLE_REDIRECT_URL}
      - APPLE_CALLBACK_URL=${APPLE_CALLBACK_URL}
      - APPLE_CLIENT_ID=${APPLE_CLIENT_ID}
      - APPLE_TEAM_ID=${APPLE_TEAM_ID}
      - APPLE_KEY_ID=${APPLE_KEY_ID}
      - COQUI_TTS_URL=${COQUI_TTS_URL:-http://localhost:5002}
      - TTS_ENGINE=${TTS_ENGINE:-google}
      - COQUI_TTS_TIMEOUT=${COQUI_TTS_TIMEOUT:-30000}
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  # Coqui TTS Service
  coqui-tts:
    container_name: youdescribex-coqui-tts
    image: ghcr.io/idiap/coqui-tts-cpu:latest
    network_mode: host
    environment:
      - MODEL_NAME=tts_models/multilingual/multi-dataset/xtts_v2
      - COQUI_TOS_AGREED=1
    entrypoint: ["/bin/bash"]
    command: ["-c", "python3 TTS/server/server.py --model_name tts_models/multilingual/multi-dataset/xtts_v2 --port 5002"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"