version: '3'
services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=30
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_ROLLING_RESTART=true
    restart: always


  youdescribe-docs:
      image: youdescribe/youdescribe-docs:master
      restart: always
      ports:
        - "0.0.0.0:4321:4321"
      labels:
        - "com.centurylinklabs.watchtower.enable=true"

  youdescribex-app:
      image: youdescribe/youdescribex-app:dev
      restart: always
      ports:
        - "0.0.0.0:3001:3001"
      labels:
        - "com.centurylinklabs.watchtower.enable=true"

  youdescribex-api:
    image: youdescribe/youdescribex-api:dev
    restart: always
    ports:
      - ${PORT}:${PORT}
      - ${GPU_PIPELINE_PORT}:${GPU_PIPELINE_PORT}
    extra_hosts:
      - 'host.docker.internal:host-gateway'
        # - ${MONGO_DB_PORT}:${MONGO_DB_PORT}
    # restart: always
    volumes:
      - /home/ubuntu/ydx_data/public:/app/public
      - /home/ubuntu/ydx_data/logs:/app/logs

    # depends_on:
    #   - mongodb
    environment:
      - INFISICAL_TOKEN=${INFISICAL_TOKEN}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  yacht:
    container_name: yacht
    restart: unless-stopped
    ports:
      - 4765:8000
    volumes:
      - yacht:/config
      - /var/run/docker.sock:/var/run/docker.sock
    image: selfhostedpro/yacht
    privileged: true
volumes:
  yacht:
